### ISSUE TITLE
Pandoc compatibility

### ISSUE THREAD

**Issue by m-fr** [s3r3t0/templates#6]
Test properly compatibility with pandoc pre and post version 3.0.0 and document them properly.

Significant changes:

- [x] LaTeX package `ulem` -> `soul`

**Comment by m-fr** [comment]
Added support for both packages in the sereto class

**Comment by s4n-cz** [comment]
This seems fine, I can see the following lines in the public templates:

```
\RequirePackage{soul}           % (Pandoc post 3.0.0)
\RequirePackage[normalem]{ulem} % (Pandoc pre 3.0.0)
```

I believe we can mark this as finished.
